import {
  Blocks,
  Wallet,
  Cross,
  Cpu,
  GraduationCap,
  Sprout,
  Camera,
  Home,
  Luggage,
  BatteryCharging,
  Factory,
  Truck,
} from "lucide-react";
import type { Sector, Company } from "./constants";

export const SECTORS: Sector[] = [
  {
    id: "agriculture",
    icon: Sprout,
    short: "Agriculture",
    full: "Agriculture & Value Chains",
    tag: "Economic Engine",
    score: 90,
    capLow: 12,
    capHigh: 22,
    irrLow: 10,
    irrHigh: 25,
    totalV: 18,
    headline: "$1.9B lost to post-harvest failures annually \u2014 before a single crop reaches market.",
    insight:
      "Cold chain and aggregation infrastructure are the two highest-ROI entry points. Tier I ventures show 15\u201325% IRR. Government's Feed Ghana Programme creates rare policy alignment.",
    subSectors: [
      { name: "Processing Facilities", pct: 35, color: "#B8D935" },
      { name: "Cold Chain & Storage", pct: 25, color: "#2E5A4D" },
      { name: "Aggregation Platforms", pct: 20, color: "#1B4D3E" },
      { name: "AgTech Investment", pct: 12, color: "#4ADE80" },
      { name: "Other", pct: 8, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Tomato Processing Facility", cap: "$2\u20134M", irr: "15\u201320%", risk: "MEDIUM" },
      { name: "Solar Cold Storage Network", cap: "$1.5\u20133M", irr: "12\u201315%", risk: "MEDIUM" },
      { name: "Cooperative Capital Fund", cap: "$1\u20132M", irr: "10\u201314%", risk: "MEDIUM" },
      { name: "AgTech Investment Portfolio", cap: "$1\u20132M", irr: "20\u201325%", risk: "HIGH" },
      { name: "Market Aggregation Centers", cap: "$0.5\u20131M", irr: "8\u201312%", risk: "LOW" },
      { name: "Agricultural Insurance Co.", cap: "$0.3\u20130.6M", irr: "Commission", risk: "LOW" },
    ],
    t2: [
      { name: "Fruit Processing Facility", cap: "$2\u20134M", irr: "14\u201318%", risk: "MEDIUM" },
      { name: "Cashew/Shea Processing", cap: "$1.5\u20133M", irr: "15\u201320%", risk: "MEDIUM" },
      { name: "Warehouse Receipt Financing", cap: "$1\u20132M", irr: "12\u201316%", risk: "MEDIUM" },
    ],
    t3: [
      { name: "Cocoa Processing Facility", cap: "$3\u20136M", irr: "15\u201322%", risk: "HIGH" },
      { name: "Integrated Agriculture Hub", cap: "$2\u20134M", irr: "12\u201318%", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Cold Chain North", pct: 68, target: "$5.5M", current: "$3.7M", months: 8 },
      { label: "Aggregation Platform", pct: 45, target: "$3.0M", current: "$1.35M", months: 12 },
      { label: "Cooperative Fund", pct: 80, target: "$2.0M", current: "$1.6M", months: 4 },
      { label: "AgTech Portfolio", pct: 30, target: "$2.0M", current: "$0.6M", months: 18 },
    ],
    activity: [
      { h: "Post-Harvest Loss Crisis Brief Published", amt: "+$2M", sig: "Bullish", date: "Feb 2026" },
      { h: "GH\u20b54.5B PFJ Phase 3 Budget Confirmed", amt: "+Policy", sig: "Bullish", date: "Mar 2026" },
      { h: "2024 Drought \u2014 436k Farmers Affected", amt: "Risk", sig: "Watch", date: "Jan 2026" },
      { h: "Cocoa Exports Hit $372.6M (Dec 2024)", amt: "+$372M", sig: "Bullish", date: "Jan 2026" },
    ],
    cross: ["financial", "technology", "infrastructure", "education"],
  },
  {
    id: "financial",
    icon: Wallet,
    short: "Financial Inclusion",
    full: "Financial Inclusion & Economic Security",
    tag: "Foundation",
    score: 91,
    capLow: 10,
    capHigh: 20,
    irrLow: 8,
    irrHigh: 25,
    totalV: 18,
    headline: "70% of Ghanaians outside formal finance \u2014 yet GH\u20b53.019T flows through mobile money annually.",
    insight:
      "Ghana is ranked #1 globally on the GSMA Mobile Money Regulatory Index (95.06%). The MSME credit gap alone is $2.2B. Tier I ventures target Kejetia market traders directly.",
    subSectors: [
      { name: "Lending & Credit", pct: 40, color: "#B8D935" },
      { name: "Mobile Money", pct: 25, color: "#2E5A4D" },
      { name: "Insurance", pct: 18, color: "#1B4D3E" },
      { name: "Savings & Susu", pct: 12, color: "#60A5FA" },
      { name: "Other", pct: 5, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Market Financial Services Platform", cap: "$1\u20133M", irr: "15\u201322%", risk: "MEDIUM" },
      { name: "Trader Working Capital Facility", cap: "$0.5\u20132M", irr: "18\u201325%", risk: "MEDIUM" },
      { name: "Digital Susu Integration", cap: "$0.2\u20130.5M", irr: "12\u201318%", risk: "LOW" },
      { name: "Market Microinsurance Bundle", cap: "$0.15\u20130.4M", irr: "Commission", risk: "LOW" },
      { name: "Financial Health Hub", cap: "$0.1\u20130.25M", irr: "Break-even", risk: "LOW" },
    ],
    t2: [
      { name: "MSME Credit Guarantee Facility", cap: "$2\u20135M", irr: "8\u201312%", risk: "MEDIUM" },
      { name: "Women's Economic Empowerment Fund", cap: "$0.5\u20131.5M", irr: "12\u201318%", risk: "MEDIUM" },
      { name: "Alternative Credit Scoring", cap: "$0.3\u20130.7M", irr: "15\u201320%", risk: "HIGH" },
    ],
    t3: [
      { name: "BRIDGE Microfinance Institution", cap: "$5\u201315M", irr: "Variable", risk: "HIGH" },
      { name: "Fintech Equity Portfolio", cap: "$1\u20135M", irr: "Variable", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Market Services Platform", pct: 72, target: "$3.0M", current: "$2.16M", months: 5 },
      { label: "Working Capital Facility", pct: 55, target: "$2.0M", current: "$1.1M", months: 9 },
      { label: "Susu Digitization", pct: 40, target: "$0.5M", current: "$0.2M", months: 10 },
      { label: "MSME Credit Guarantee", pct: 20, target: "$5.0M", current: "$1.0M", months: 20 },
    ],
    activity: [
      { h: "Bank of Ghana Digital Credit Directive Expands", amt: "+Policy", sig: "Bullish", date: "Mar 2026" },
      { h: "MoMo Interoperability Live \u2014 All Networks", amt: "+Access", sig: "Bullish", date: "Jan 2026" },
      { h: "SME Financing Gap Widens to $2.2B", amt: "$2.2B", sig: "Watch", date: "Feb 2026" },
      { h: "Ghana Ranked #1 on GSMA MoMo Index", amt: "95.06", sig: "Bullish", date: "Nov 2025" },
    ],
    cross: ["technology", "agriculture", "health", "infrastructure"],
  },
  {
    id: "technology",
    icon: Cpu,
    short: "Technology",
    full: "Technology & Innovation",
    tag: "Growth Engine",
    score: 89,
    capLow: 8,
    capHigh: 15,
    irrLow: 15,
    irrHigh: 30,
    totalV: 15,
    headline: "Kejetia \u2014 10,000+ vendors, West Africa's largest market \u2014 is BRIDGE's flagship tech platform.",
    insight:
      "Ghana has 400+ active startups but virtually no Series A capital in-country. BRIDGE fills the missing middle with Kejetia as the proof-of-concept anchor and a $5\u201310M growth fund.",
    subSectors: [
      { name: "Platform / SaaS", pct: 35, color: "#B8D935" },
      { name: "Investment / VC", pct: 28, color: "#8B5CF6" },
      { name: "Talent & Training", pct: 18, color: "#2E5A4D" },
      { name: "FinTech", pct: 12, color: "#1B4D3E" },
      { name: "Other", pct: 7, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Kejetia Digital Platform", cap: "$3\u20135M", irr: "18\u201325%", risk: "MEDIUM" },
      { name: "BRIDGE Growth Fund \u2014 Tech", cap: "$5\u201310M", irr: "20\u201330%", risk: "HIGH" },
      { name: "Tech Talent Bridge Program", cap: "$0.3\u20130.6M", irr: "Break-even", risk: "LOW" },
      { name: "Fintech Portfolio", cap: "$2\u20134M", irr: "15\u201325%", risk: "HIGH" },
      { name: "Digital Apprenticeship", cap: "$0.2\u20130.4M", irr: "Social", risk: "LOW" },
    ],
    t2: [
      { name: "Market Platform Replication", cap: "$2\u20134M", irr: "15\u201322%", risk: "MEDIUM" },
      { name: "AgTech Investment Portfolio", cap: "$1.5\u20133M", irr: "20\u201328%", risk: "HIGH" },
      { name: "Rural Digital Access", cap: "$1\u20132M", irr: "Social", risk: "MEDIUM" },
    ],
    t3: [
      { name: "AI/ML Center of Excellence", cap: "$2\u20135M", irr: "Variable", risk: "HIGH" },
      { name: "Data Center Co-Investment", cap: "$3\u20138M", irr: "Variable", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Kejetia Platform", pct: 85, target: "$5.0M", current: "$4.25M", months: 2 },
      { label: "BRIDGE Growth Fund", pct: 50, target: "$10M", current: "$5.0M", months: 10 },
      { label: "Fintech Portfolio", pct: 35, target: "$4.0M", current: "$1.4M", months: 14 },
      { label: "Market Replication", pct: 15, target: "$4.0M", current: "$0.6M", months: 22 },
    ],
    activity: [
      { h: "Kejetia Phase 2 \u2014 3,000 New Vendors Onboarded", amt: "+3k", sig: "Bullish", date: "Mar 2026" },
      { h: "Ghana Joins Smart Africa Alliance", amt: "+Policy", sig: "Bullish", date: "Feb 2026" },
      { h: "Series A Desert \u2014 Only 2 Deals in 2025", amt: "-", sig: "Watch", date: "Jan 2026" },
      { h: "Disrupt Africa: Ghana Leads West Africa Funding", amt: "+28%", sig: "Bullish", date: "Dec 2025" },
    ],
    cross: ["agriculture", "financial", "health", "education"],
  },
  {
    id: "energy",
    icon: BatteryCharging,
    short: "Energy",
    full: "Energy & Renewable Resources",
    tag: "Foundation",
    score: 88,
    capLow: 12,
    capHigh: 22,
    irrLow: 12,
    irrHigh: 22,
    totalV: 14,
    headline: "Power outages cost Ghana $924M/yr \u2014 solar irradiance 4.5\u20136 kWh/m\u00b2 is Africa-class.",
    insight:
      "$200M Clean Cooking Outcome Bond and 1GW Solar Park expansion signal unprecedented government commitment. Distributed solar shows 15\u201322% IRR on a structurally falling cost curve.",
    subSectors: [
      { name: "Solar Solutions", pct: 40, color: "#B8D935" },
      { name: "Clean Cooking", pct: 22, color: "#F59E0B" },
      { name: "Mini-Grid Dev.", pct: 18, color: "#2E5A4D" },
      { name: "Training", pct: 12, color: "#1B4D3E" },
      { name: "Other", pct: 8, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Ghana Solar Solutions Company", cap: "$3\u20136M", irr: "15\u201322%", risk: "MEDIUM" },
      { name: "Clean Cooking Distribution Network", cap: "$2\u20134M", irr: "12\u201318%", risk: "MEDIUM" },
      { name: "Solar Technician Training Academy", cap: "$0.5\u20131M", irr: "Social", risk: "LOW" },
      { name: "Solar-Powered Cold Storage Network", cap: "$1.5\u20133M", irr: "12\u201316%", risk: "MEDIUM" },
      { name: "Energy Efficiency Services Company", cap: "$0.5\u20131M", irr: "14\u201318%", risk: "LOW" },
    ],
    t2: [
      { name: "Community Mini-Grid Development", cap: "$2\u20135M", irr: "14\u201320%", risk: "MEDIUM" },
      { name: "Solar Equipment Import & Dist.", cap: "$1\u20132M", irr: "15\u201320%", risk: "MEDIUM" },
      { name: "Residential Solar Financing", cap: "$1\u20132M", irr: "12\u201318%", risk: "MEDIUM" },
    ],
    t3: [
      { name: "EV Charging Infrastructure", cap: "$2\u20134M", irr: "12\u201318%", risk: "HIGH" },
      { name: "Battery Storage Systems", cap: "$2\u20135M", irr: "15\u201322%", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Ghana Solar Solutions", pct: 65, target: "$6.0M", current: "$3.9M", months: 7 },
      { label: "Clean Cooking Network", pct: 48, target: "$4.0M", current: "$1.92M", months: 11 },
      { label: "Mini-Grid Dev. Co.", pct: 25, target: "$5.0M", current: "$1.25M", months: 18 },
      { label: "Solar Equipment Dist.", pct: 35, target: "$2.0M", current: "$0.7M", months: 14 },
    ],
    activity: [
      { h: "Solar Park: 200MW to 1GW Expansion Confirmed", amt: "+800MW", sig: "Bullish", date: "Mar 2026" },
      { h: "$200M Clean Cooking Outcome Bond Now Open", amt: "$200M", sig: "Bullish", date: "Feb 2026" },
      { h: "Dumsor Returns \u2014 Business Losses Mount", amt: "-$900M", sig: "Watch", date: "Jan 2026" },
      { h: "IRENA: Solar Costs Down 89% Since 2010", amt: "-89%", sig: "Bullish", date: "Dec 2025" },
    ],
    cross: ["agriculture", "manufacturing", "transportation", "infrastructure"],
  },
  {
    id: "infrastructure",
    icon: Blocks,
    short: "Infrastructure",
    full: "Infrastructure & Basic Services",
    tag: "Foundation",
    score: 87,
    capLow: 8,
    capHigh: 15,
    irrLow: 8,
    irrHigh: 20,
    totalV: 15,
    headline: "$40B+ infrastructure gap \u2014 2026 Budget allocates GH\u20b518B to infrastructure alone.",
    insight:
      "Infrastructure underpins every other BRIDGE sector. Rural connectivity is the multiplier. Build24 pillar creates direct co-investment pathways across roads, water, and digital.",
    subSectors: [
      { name: "Water Systems", pct: 30, color: "#B8D935" },
      { name: "Connectivity", pct: 28, color: "#2E5A4D" },
      { name: "Roads & Logistics", pct: 22, color: "#1B4D3E" },
      { name: "Digital Infra.", pct: 12, color: "#60A5FA" },
      { name: "Sanitation", pct: 8, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Rural Connectivity Platform", cap: "$2\u20134M", irr: "12\u201318%", risk: "MEDIUM" },
      { name: "Water Systems Management Co.", cap: "$2\u20134M", irr: "10\u201315%", risk: "LOW" },
      { name: "Last-Mile Logistics Network", cap: "$1.5\u20133M", irr: "14\u201320%", risk: "MEDIUM" },
      { name: "Community Sanitation Services", cap: "$0.5\u20131.5M", irr: "8\u201312%", risk: "LOW" },
      { name: "Digital Infrastructure Co.", cap: "$2\u20134M", irr: "15\u201320%", risk: "MEDIUM" },
    ],
    t2: [
      { name: "Urban Infrastructure Fund", cap: "$3\u20136M", irr: "10\u201315%", risk: "MEDIUM" },
      { name: "Telecoms Tower Fund", cap: "$2\u20134M", irr: "14\u201318%", risk: "MEDIUM" },
    ],
    t3: [
      { name: "Waste Management Company", cap: "$2\u20135M", irr: "12\u201318%", risk: "HIGH" },
      { name: "Smart City Infrastructure", cap: "$3\u20137M", irr: "Variable", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Rural Connectivity", pct: 55, target: "$4.0M", current: "$2.2M", months: 10 },
      { label: "Water Systems Co.", pct: 70, target: "$4.0M", current: "$2.8M", months: 6 },
      { label: "Last-Mile Logistics", pct: 40, target: "$3.0M", current: "$1.2M", months: 13 },
      { label: "Urban Infra. Fund", pct: 20, target: "$6.0M", current: "$1.2M", months: 22 },
    ],
    activity: [
      {
        h: "GH\u20b518B+ Infra Allocation Locked \u2014 2026 Budget",
        amt: "+Policy",
        sig: "Bullish",
        date: "Mar 2026",
      },
      { h: "Roads Authority Fast-Track Program Launched", amt: "+Ops", sig: "Bullish", date: "Feb 2026" },
      { h: "Water & Sanitation: Only 27% Coverage", amt: "-73%", sig: "Watch", date: "Jan 2026" },
    ],
    cross: ["transportation", "energy", "agriculture", "technology"],
  },
  {
    id: "health",
    icon: Cross,
    short: "Health Systems",
    full: "Health Systems & Wellbeing",
    tag: "Human Capital",
    score: 83,
    capLow: 8,
    capHigh: 16,
    irrLow: 8,
    irrHigh: 22,
    totalV: 15,
    headline: "0.1 doctors per 1,000 vs WHO benchmark of 1.0 \u2014 supply chain leakage at 30\u201340%.",
    insight:
      "Community health worker platforms are the fastest path to measurable impact. NHIA digital claims expansion creates direct reimbursement pathways for BRIDGE-backed primary care ventures.",
    subSectors: [
      { name: "Primary Care", pct: 32, color: "#B8D935" },
      { name: "Supply Chain", pct: 28, color: "#EF4444" },
      { name: "Digital Health", pct: 20, color: "#2E5A4D" },
      { name: "Diagnostics", pct: 12, color: "#1B4D3E" },
      { name: "Health Finance", pct: 8, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Community Health Worker Platform", cap: "$1.5\u20133M", irr: "Social", risk: "LOW" },
      { name: "Medical Supply Chain Co.", cap: "$2\u20134M", irr: "14\u201320%", risk: "MEDIUM" },
      { name: "Diagnostic Services Company", cap: "$1.5\u20133M", irr: "18\u201322%", risk: "MEDIUM" },
      { name: "NHIS Claims Processing Platform", cap: "$0.5\u20131M", irr: "12\u201316%", risk: "MEDIUM" },
    ],
    t2: [
      { name: "Telemedicine Network", cap: "$1\u20132.5M", irr: "12\u201318%", risk: "MEDIUM" },
      { name: "Health Finance Platform", cap: "$0.5\u20131.5M", irr: "10\u201315%", risk: "MEDIUM" },
      { name: "Pharmaceutical Distribution", cap: "$1.5\u20133M", irr: "14\u201320%", risk: "MEDIUM" },
    ],
    t3: [
      { name: "Medical Training Institute", cap: "$2\u20134M", irr: "Social", risk: "MEDIUM" },
      { name: "HealthTech Investment Portfolio", cap: "$1\u20133M", irr: "18\u201325%", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Supply Chain Co.", pct: 60, target: "$4.0M", current: "$2.4M", months: 8 },
      { label: "Community HW Platform", pct: 75, target: "$3.0M", current: "$2.25M", months: 5 },
      { label: "Telemedicine Network", pct: 30, target: "$2.5M", current: "$0.75M", months: 16 },
      { label: "Diagnostic Services", pct: 45, target: "$3.0M", current: "$1.35M", months: 12 },
    ],
    activity: [
      { h: "NHIA Expands Digital Claims Processing", amt: "+Access", sig: "Bullish", date: "Feb 2026" },
      { h: "GH\u20b58.2B Health Allocation \u2014 12% YoY Increase", amt: "+12%", sig: "Bullish", date: "Mar 2026" },
      { h: "Workforce Gap: 40k More Health Workers Needed", amt: "-40k", sig: "Watch", date: "Jan 2026" },
    ],
    cross: ["technology", "financial", "manufacturing", "education"],
  },
  {
    id: "education",
    icon: GraduationCap,
    short: "Education",
    full: "Education & Skills",
    tag: "Human Capital",
    score: 85,
    capLow: 16.5,
    capHigh: 33.5,
    irrLow: 10,
    irrHigh: 25,
    totalV: 15,
    headline: "60% of graduates underemployed within 2 years \u2014 400% tertiary growth, zero market alignment.",
    insight:
      "TVET transformation is the highest-leverage education investment. Government's GH\u20b52B commitment creates direct co-investment pathways. Diaspora mentorship shows exceptional social return at near-zero cost.",
    subSectors: [
      { name: "TVET & Vocational", pct: 38, color: "#B8D935" },
      { name: "Scholarships", pct: 22, color: "#0EA5E9" },
      { name: "Skills Bootcamps", pct: 18, color: "#2E5A4D" },
      { name: "EdTech Investment", pct: 14, color: "#1B4D3E" },
      { name: "Other", pct: 8, color: "#E5E7EB" },
    ],
    t1: [
      { name: "TVET Partnership Program", cap: "$3\u20136M", irr: "Social+", risk: "MEDIUM" },
      { name: "Diaspora Scholarship Fund", cap: "$2\u20133M", irr: "Social+", risk: "LOW" },
      { name: "Skills Bootcamp Network", cap: "$1.5\u20133M", irr: "10\u201315%", risk: "LOW" },
      { name: "Diaspora Mentorship Platform", cap: "$0.5\u20131M", irr: "Social", risk: "LOW" },
      { name: "EdTech Investment Portfolio", cap: "$1.5\u20133M", irr: "20\u201328%", risk: "HIGH" },
    ],
    t2: [
      { name: "TVET Regional Expansion", cap: "$2\u20134M", irr: "Social+", risk: "MEDIUM" },
      { name: "Professional Dev. Academy", cap: "$1\u20132M", irr: "12\u201318%", risk: "MEDIUM" },
    ],
    t3: [
      { name: "BRIDGE Training Center Kumasi", cap: "$2\u20134M", irr: "12\u201318%", risk: "MEDIUM" },
      { name: "Research Partnership", cap: "$0.5\u20131M", irr: "Social", risk: "LOW" },
    ],
    pipeline: [
      { label: "TVET Partnership", pct: 58, target: "$6.0M", current: "$3.48M", months: 9 },
      { label: "Scholarship Fund", pct: 80, target: "$3.0M", current: "$2.4M", months: 4 },
      { label: "Skills Bootcamp Net.", pct: 45, target: "$3.0M", current: "$1.35M", months: 12 },
      { label: "EdTech Portfolio", pct: 20, target: "$3.0M", current: "$0.6M", months: 20 },
    ],
    activity: [
      { h: "MoE TVET Overhaul \u2014 GH\u20b52B Committed", amt: "+Policy", sig: "Bullish", date: "Jan 2026" },
      { h: "Ghana Youth Unemployment Hits 13.4%", amt: "-", sig: "Watch", date: "Feb 2026" },
      { h: "Diaspora Fellowship: 120 Placements Confirmed", amt: "+120", sig: "Bullish", date: "Mar 2026" },
    ],
    cross: ["technology", "manufacturing", "agriculture", "health"],
  },
  {
    id: "housing",
    icon: Home,
    short: "Housing",
    full: "Housing & Real Estate",
    tag: "Foundation",
    score: 82,
    capLow: 15,
    capHigh: 25,
    irrLow: 10,
    irrHigh: 20,
    totalV: 11,
    headline: "2 million unit deficit growing 200k/yr \u2014 mortgage penetration below 2% of GDP.",
    insight:
      "The $6.65B remittance flow already includes significant informal housing spend. NHA PPP framework opens private entry at scale. Diaspora housing products meet proven, demonstrated demand.",
    subSectors: [
      { name: "Affordable Dev.", pct: 38, color: "#B8D935" },
      { name: "Construction Finance", pct: 28, color: "#14B8A6" },
      { name: "Diaspora Products", pct: 18, color: "#2E5A4D" },
      { name: "Rental Management", pct: 10, color: "#1B4D3E" },
      { name: "Materials", pct: 6, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Affordable Housing Developer", cap: "$8\u201315M", irr: "14\u201320%", risk: "MEDIUM" },
      { name: "Construction Finance Platform", cap: "$4\u20138M", irr: "12\u201318%", risk: "MEDIUM" },
    ],
    t2: [
      { name: "Diaspora Housing Product", cap: "$2\u20134M", irr: "10\u201315%", risk: "LOW" },
      { name: "Rental Management Platform", cap: "$1\u20132M", irr: "12\u201318%", risk: "LOW" },
    ],
    t3: [{ name: "Building Materials Supply Co.", cap: "$2\u20134M", irr: "14\u201318%", risk: "MEDIUM" }],
    pipeline: [
      { label: "Affordable Housing", pct: 40, target: "$15M", current: "$6.0M", months: 18 },
      { label: "Construction Finance", pct: 55, target: "$8.0M", current: "$4.4M", months: 10 },
      { label: "Diaspora Housing Prod.", pct: 70, target: "$4.0M", current: "$2.8M", months: 6 },
      { label: "Rental Management", pct: 30, target: "$2.0M", current: "$0.6M", months: 16 },
    ],
    activity: [
      { h: "NHA PPP Framework Opens Private Entry", amt: "+Policy", sig: "Bullish", date: "Feb 2026" },
      { h: "Mortgage Penetration Still Below 2%", amt: "<2%", sig: "Watch", date: "Jan 2026" },
      { h: "Diaspora Housing Survey: 78% Interested", amt: "+Demand", sig: "Bullish", date: "Dec 2025" },
    ],
    cross: ["financial", "manufacturing", "infrastructure", "transportation"],
  },
  {
    id: "manufacturing",
    icon: Factory,
    short: "Manufacturing",
    full: "Manufacturing & Light Industry",
    tag: "Economic Engine",
    score: 81,
    capLow: 15,
    capHigh: 30,
    irrLow: 12,
    irrHigh: 22,
    totalV: 14,
    headline: "Ghana imports $8B+ of goods it has every raw input to produce domestically.",
    insight:
      "GH\u20b55B manufacturing incentive package plus 5-year tax holiday for domestic manufacturers in 2026 Budget. Agro-processing is lowest-risk entry point \u2014 feeds directly into Agriculture cold chain.",
    subSectors: [
      { name: "Agro-Processing", pct: 35, color: "#B8D935" },
      { name: "Packaging", pct: 22, color: "#6366F1" },
      { name: "Consumer Goods", pct: 20, color: "#2E5A4D" },
      { name: "Industrial Training", pct: 14, color: "#1B4D3E" },
      { name: "Export Processing", pct: 9, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Agro-Processing Facility", cap: "$5\u201310M", irr: "15\u201320%", risk: "MEDIUM" },
      { name: "Packaging Solutions Company", cap: "$3\u20136M", irr: "14\u201318%", risk: "MEDIUM" },
      { name: "Industrial Training Centre", cap: "$1\u20132M", irr: "Social+", risk: "LOW" },
    ],
    t2: [
      { name: "Consumer Goods Manufacturer", cap: "$4\u20138M", irr: "14\u201320%", risk: "MEDIUM" },
      { name: "Pharmaceutical Manufacturing", cap: "$3\u20136M", irr: "15\u201322%", risk: "HIGH" },
      { name: "Textile & Garments Factory", cap: "$2\u20134M", irr: "12\u201318%", risk: "MEDIUM" },
    ],
    t3: [
      { name: "Export Processing Facility", cap: "$5\u201310M", irr: "15\u201322%", risk: "HIGH" },
      { name: "Industrial Park Co-Investment", cap: "$5\u201310M", irr: "12\u201318%", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Agro-Processing Fac.", pct: 45, target: "$10M", current: "$4.5M", months: 14 },
      { label: "Packaging Solutions", pct: 60, target: "$6.0M", current: "$3.6M", months: 9 },
      { label: "Consumer Goods Mfg.", pct: 20, target: "$8.0M", current: "$1.6M", months: 22 },
      { label: "Pharma Manufacturing", pct: 10, target: "$6.0M", current: "$0.6M", months: 30 },
    ],
    activity: [
      { h: "GH\u20b55B Manufacturing Incentive Package Confirmed", amt: "+Policy", sig: "Bullish", date: "Mar 2026" },
      { h: "5-Year Tax Holiday for Domestic Manufacturers", amt: "+Tax", sig: "Bullish", date: "Mar 2026" },
      { h: "Import Bill Grows to $8.2B \u2014 Opportunity Widens", amt: "$8.2B", sig: "Watch", date: "Feb 2026" },
    ],
    cross: ["agriculture", "energy", "transportation", "education"],
  },
  {
    id: "transportation",
    icon: Truck,
    short: "Transportation",
    full: "Transportation & Logistics",
    tag: "Foundation",
    score: 79,
    capLow: 10,
    capHigh: 22,
    irrLow: 10,
    irrHigh: 22,
    totalV: 14,
    headline: "Logistics costs 2-3x global average \u2014 cold chain alone is a $900M annual opportunity.",
    insight:
      "Every sector's growth multiplier. Tema Port Phase 2 ($1.5B) and Boankra Inland Port ($308M) create infrastructure tailwinds. Cold Chain Ghana directly addresses the $1.9B post-harvest loss problem.",
    subSectors: [
      { name: "Cold Chain", pct: 32, color: "#B8D935" },
      { name: "Last-Mile Delivery", pct: 28, color: "#64748B" },
      { name: "Fleet & Freight", pct: 20, color: "#2E5A4D" },
      { name: "Port & Warehousing", pct: 13, color: "#1B4D3E" },
      { name: "Other", pct: 7, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Cold Chain Ghana", cap: "$3\u20136M", irr: "16\u201322%", risk: "MEDIUM" },
      { name: "Ghana Last Mile Delivery Co.", cap: "$2\u20134M", irr: "14\u201320%", risk: "MEDIUM" },
      { name: "Fleet Management Services", cap: "$1.5\u20133M", irr: "14\u201318%", risk: "LOW" },
      { name: "Logistics Technology Platform", cap: "$1\u20132M", irr: "20\u201325%", risk: "MEDIUM" },
      { name: "Logistics Training Academy", cap: "$0.5\u20131M", irr: "Social+", risk: "LOW" },
    ],
    t2: [
      { name: "Pharma Cold Chain Services", cap: "$1.5\u20133M", irr: "16\u201322%", risk: "MEDIUM" },
      { name: "Agricultural Aggregation Transport", cap: "$2\u20134M", irr: "14\u201318%", risk: "MEDIUM" },
      { name: "Warehousing & Distribution", cap: "$2\u20134M", irr: "12\u201316%", risk: "MEDIUM" },
    ],
    t3: [
      { name: "Inland Port Services", cap: "$3\u20136M", irr: "12\u201318%", risk: "HIGH" },
      { name: "Rail Logistics Integration", cap: "$2\u20135M", irr: "12\u201316%", risk: "HIGH" },
    ],
    pipeline: [
      { label: "Cold Chain Ghana", pct: 50, target: "$6.0M", current: "$3.0M", months: 12 },
      { label: "Last Mile Delivery", pct: 40, target: "$4.0M", current: "$1.6M", months: 14 },
      { label: "Logistics Tech Platform", pct: 65, target: "$2.0M", current: "$1.3M", months: 7 },
      { label: "Fleet Management", pct: 35, target: "$3.0M", current: "$1.05M", months: 15 },
    ],
    activity: [
      { h: "Tema Port Phase 2 \u2014 $1.5B Investment Confirmed", amt: "$1.5B", sig: "Bullish", date: "Feb 2026" },
      { h: "Connect24: 18% Logistics Cost Reduction Target", amt: "-18%", sig: "Bullish", date: "Jan 2026" },
      { h: "Cold Chain Revenue Potential: $900M/yr", amt: "$900M", sig: "Bullish", date: "Dec 2025" },
    ],
    cross: ["agriculture", "energy", "manufacturing", "infrastructure"],
  },
  {
    id: "tourism",
    icon: Luggage,
    short: "Tourism",
    full: "Tourism & Hospitality",
    tag: "Growth Engine",
    score: 76,
    capLow: 10,
    capHigh: 18,
    irrLow: 10,
    irrHigh: 22,
    totalV: 13,
    headline: "Year of Return generated $3.3B in 2019 \u2014 the infrastructure to sustain it was never built.",
    insight:
      "Cultural tourism carries diaspora demand that cannot be manufactured. Heritage circuits and hospitality training are structurally underbuilt. YoR proved the demand exists at scale.",
    subSectors: [
      { name: "Heritage Tourism", pct: 32, color: "#B8D935" },
      { name: "Hospitality Training", pct: 25, color: "#EC4899" },
      { name: "Eco-Tourism", pct: 22, color: "#2E5A4D" },
      { name: "Cultural Platforms", pct: 14, color: "#1B4D3E" },
      { name: "Other", pct: 7, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Heritage Tourism Network", cap: "$3\u20136M", irr: "14\u201320%", risk: "MEDIUM" },
      { name: "Hospitality Training Academy", cap: "$1.5\u20133M", irr: "Social+", risk: "LOW" },
    ],
    t2: [
      { name: "Eco-Tourism Development Fund", cap: "$2\u20134M", irr: "12\u201318%", risk: "MEDIUM" },
      { name: "Cultural Experience Platform", cap: "$1\u20132M", irr: "15\u201322%", risk: "MEDIUM" },
    ],
    t3: [{ name: "Destination Development Company", cap: "$3\u20136M", irr: "12\u201318%", risk: "HIGH" }],
    pipeline: [
      { label: "Heritage Tourism Net.", pct: 50, target: "$6.0M", current: "$3.0M", months: 11 },
      { label: "Hospitality Academy", pct: 65, target: "$3.0M", current: "$1.95M", months: 7 },
      { label: "Eco-Tourism Fund", pct: 25, target: "$4.0M", current: "$1.0M", months: 18 },
      { label: "Cultural Platform", pct: 35, target: "$2.0M", current: "$0.7M", months: 15 },
    ],
    activity: [
      { h: "Ghana Tourism Authority New Destination Brand", amt: "+Brand", sig: "Bullish", date: "Jan 2026" },
      { h: "Accra MICE Tourism Up 35% \u2014 Conference Demand", amt: "+35%", sig: "Bullish", date: "Feb 2026" },
      { h: "Hotel Occupancy Still 58% National Average", amt: "58%", sig: "Watch", date: "Dec 2025" },
    ],
    cross: ["creative", "housing", "transportation", "infrastructure"],
  },
  {
    id: "creative",
    icon: Camera,
    short: "Creative Industries",
    full: "Sports, Entertainment & Creative",
    tag: "Growth Engine",
    score: 78,
    capLow: 10,
    capHigh: 20.5,
    irrLow: 10,
    irrHigh: 28,
    totalV: 14,
    headline: "Afrobeats is global. Ghana captures less than 15% of its own IP value.",
    insight:
      "Content production infrastructure, talent pipelines, and digital distribution are structurally absent. First movers build durable IP advantages. Sports infrastructure doubles as community assets.",
    subSectors: [
      { name: "Content Production", pct: 30, color: "#B8D935" },
      { name: "Talent Development", pct: 25, color: "#F97316" },
      { name: "IP Monetisation", pct: 22, color: "#2E5A4D" },
      { name: "Sports Infrastructure", pct: 15, color: "#1B4D3E" },
      { name: "Other", pct: 8, color: "#E5E7EB" },
    ],
    t1: [
      { name: "Content Production Studio", cap: "$2\u20134M", irr: "15\u201322%", risk: "MEDIUM" },
      { name: "Talent Development Platform", cap: "$1.5\u20133M", irr: "Social+", risk: "LOW" },
    ],
    t2: [
      { name: "IP Monetisation Platform", cap: "$1.5\u20133M", irr: "20\u201328%", risk: "HIGH" },
      { name: "Sports Infrastructure Fund", cap: "$3\u20136M", irr: "10\u201315%", risk: "MEDIUM" },
    ],
    t3: [{ name: "Creative Hub Network", cap: "$2\u20135M", irr: "12\u201318%", risk: "MEDIUM" }],
    pipeline: [
      { label: "Content Studio", pct: 55, target: "$4.0M", current: "$2.2M", months: 10 },
      { label: "Talent Platform", pct: 40, target: "$3.0M", current: "$1.2M", months: 13 },
      { label: "IP Monetisation", pct: 20, target: "$3.0M", current: "$0.6M", months: 20 },
      { label: "Sports Infra. Fund", pct: 15, target: "$6.0M", current: "$0.9M", months: 26 },
    ],
    activity: [
      { h: "Ghana Music Awards \u2014 40% Viewership Growth", amt: "+40%", sig: "Bullish", date: "Jan 2026" },
      { h: "Afrobeats Streams Exceed 45M Monthly Listeners", amt: "45M", sig: "Bullish", date: "Feb 2026" },
      { h: "IP Piracy Costs Creative Sector $400M+ Annually", amt: "-$400M", sig: "Watch", date: "Dec 2025" },
    ],
    cross: ["technology", "tourism", "education", "infrastructure"],
  },
];

export const COMPANIES: Record<string, Company[]> = {
  agriculture: [
    { r: 1, name: "Cocobod Ghana", tk: "#COC", chg: "+4.2%", val: "$2.1B", sc: 88 },
    { r: 2, name: "Yedent Agro", tk: "#YED", chg: "+2.8%", val: "$340M", sc: 81 },
    { r: 3, name: "MOFA GH", tk: "#MFA", chg: "+1.1%", val: "$180M", sc: 76 },
    { r: 4, name: "Pineapple Industries", tk: "#PIN", chg: "-0.6%", val: "$95M", sc: 68 },
    { r: 5, name: "Akate Farms", tk: "#AKF", chg: "+3.3%", val: "$72M", sc: 64 },
  ],
  financial: [
    { r: 1, name: "Fidelity Bank Ghana", tk: "#FBG", chg: "+6.1%", val: "$1.4B", sc: 91 },
    { r: 2, name: "MTN MoMo", tk: "#MTN", chg: "+3.5%", val: "$3.2B", sc: 88 },
    { r: 3, name: "Zeepay", tk: "#ZPY", chg: "+2.2%", val: "$280M", sc: 83 },
    { r: 4, name: "Stanbic IBTC", tk: "#SIB", chg: "+0.9%", val: "$620M", sc: 76 },
    { r: 5, name: "CalBank Ghana", tk: "#CAL", chg: "-0.4%", val: "$310M", sc: 71 },
  ],
  technology: [
    { r: 1, name: "Hubtel Ghana", tk: "#HBT", chg: "+8.4%", val: "$420M", sc: 91 },
    { r: 2, name: "Rancard Solutions", tk: "#RNC", chg: "+5.1%", val: "$95M", sc: 84 },
    { r: 3, name: "mPharma", tk: "#MPH", chg: "+3.7%", val: "$240M", sc: 79 },
    { r: 4, name: "ExpressPay GH", tk: "#EXP", chg: "+2.0%", val: "$68M", sc: 74 },
    { r: 5, name: "Leti Arts", tk: "#LTA", chg: "-1.2%", val: "$22M", sc: 65 },
  ],
  energy: [
    { r: 1, name: "BXC Energia", tk: "#BXC", chg: "+5.8%", val: "$890M", sc: 90 },
    { r: 2, name: "Amandi Energy", tk: "#AMD", chg: "+3.2%", val: "$560M", sc: 85 },
    { r: 3, name: "Volta River Auth.", tk: "#VRA", chg: "+1.4%", val: "$1.1B", sc: 80 },
    { r: 4, name: "BOST Ghana", tk: "#BST", chg: "-0.8%", val: "$310M", sc: 71 },
    { r: 5, name: "SolarKal GH", tk: "#SKL", chg: "+4.1%", val: "$48M", sc: 68 },
  ],
  infrastructure: [
    { r: 1, name: "Ghana Highway Auth.", tk: "#GHA", chg: "+2.9%", val: "$420M", sc: 85 },
    { r: 2, name: "GWCL", tk: "#GWC", chg: "+1.8%", val: "$280M", sc: 80 },
    { r: 3, name: "Quaye Group", tk: "#QGP", chg: "+3.3%", val: "$190M", sc: 75 },
    { r: 4, name: "Constec GH", tk: "#CST", chg: "-0.5%", val: "$140M", sc: 68 },
    { r: 5, name: "Aluworks", tk: "#ALW", chg: "+0.7%", val: "$88M", sc: 62 },
  ],
  education: [
    { r: 1, name: "KNUST Holdings", tk: "#KNU", chg: "+3.1%", val: "$380M", sc: 86 },
    { r: 2, name: "Accra Academy", tk: "#AAC", chg: "+2.4%", val: "$95M", sc: 78 },
    { r: 3, name: "Edubridge GH", tk: "#EDB", chg: "+5.2%", val: "$48M", sc: 73 },
    { r: 4, name: "Ghana Book Trust", tk: "#GBT", chg: "+1.0%", val: "$32M", sc: 66 },
    { r: 5, name: "AfriLearn", tk: "#AFL", chg: "-0.3%", val: "$18M", sc: 61 },
  ],
  health: [
    { r: 1, name: "Rabito Clinic", tk: "#RAB", chg: "+4.3%", val: "$280M", sc: 87 },
    { r: 2, name: "mPharma Health", tk: "#MPH", chg: "+3.1%", val: "$340M", sc: 82 },
    { r: 3, name: "Lister Hospital", tk: "#LST", chg: "+1.6%", val: "$195M", sc: 76 },
    { r: 4, name: "Medlab GH", tk: "#MED", chg: "-0.9%", val: "$88M", sc: 70 },
    { r: 5, name: "KCCR", tk: "#KCC", chg: "+2.0%", val: "$62M", sc: 65 },
  ],
  housing: [
    { r: 1, name: "Regimanuel Gray", tk: "#RGY", chg: "+4.8%", val: "$520M", sc: 84 },
    { r: 2, name: "Devtraco Plus", tk: "#DVT", chg: "+3.2%", val: "$310M", sc: 79 },
    { r: 3, name: "Berock Ventures", tk: "#BRK", chg: "+2.1%", val: "$240M", sc: 74 },
    { r: 4, name: "SSNIT Housing", tk: "#SSH", chg: "+0.6%", val: "$480M", sc: 68 },
    { r: 5, name: "GoldKey Props", tk: "#GKP", chg: "-0.2%", val: "$95M", sc: 62 },
  ],
  manufacturing: [
    { r: 1, name: "Unilever Ghana", tk: "#UNL", chg: "+3.9%", val: "$780M", sc: 83 },
    { r: 2, name: "Fan Milk Ghana", tk: "#FML", chg: "+2.6%", val: "$420M", sc: 78 },
    { r: 3, name: "Benso Oil", tk: "#BNO", chg: "+1.8%", val: "$190M", sc: 73 },
    { r: 4, name: "Pioneer Food Cannon", tk: "#PFC", chg: "-1.1%", val: "$140M", sc: 65 },
    { r: 5, name: "Aluworks", tk: "#ALW", chg: "+0.5%", val: "$88M", sc: 60 },
  ],
  transportation: [
    { r: 1, name: "Antrak Ghana", tk: "#ANT", chg: "+5.2%", val: "$380M", sc: 80 },
    { r: 2, name: "Ghana Ports Auth.", tk: "#GPA", chg: "+2.8%", val: "$1.2B", sc: 76 },
    { r: 3, name: "Starlite Trans.", tk: "#STL", chg: "+1.4%", val: "$95M", sc: 71 },
    { r: 4, name: "DHL Ghana", tk: "#DHL", chg: "+0.9%", val: "$280M", sc: 66 },
    { r: 5, name: "Quaynor Express", tk: "#QEX", chg: "-0.6%", val: "$48M", sc: 58 },
  ],
  tourism: [
    { r: 1, name: "La Palm Royal", tk: "#LPR", chg: "+4.1%", val: "$310M", sc: 78 },
    { r: 2, name: "Accra City Hotel", tk: "#ACH", chg: "+2.9%", val: "$195M", sc: 73 },
    { r: 3, name: "Kempinski GH", tk: "#KMP", chg: "+3.8%", val: "$480M", sc: 70 },
    { r: 4, name: "Heritage GH", tk: "#HGH", chg: "+1.2%", val: "$88M", sc: 64 },
    { r: 5, name: "Labadi Beach Hotel", tk: "#LBH", chg: "-0.7%", val: "$140M", sc: 60 },
  ],
  creative: [
    { r: 1, name: "TV3 Ghana", tk: "#TV3", chg: "+5.6%", val: "$180M", sc: 79 },
    { r: 2, name: "EIB Network", tk: "#EIB", chg: "+3.4%", val: "$95M", sc: 74 },
    { r: 3, name: "Ameyaw Konsult", tk: "#AMK", chg: "+2.1%", val: "$28M", sc: 69 },
    { r: 4, name: "Black Star Studios", tk: "#BSS", chg: "+4.8%", val: "$42M", sc: 65 },
    { r: 5, name: "GhanaWeb Media", tk: "#GWM", chg: "-0.3%", val: "$38M", sc: 60 },
  ],
};
